services:
  medico:
    build:
      context: ./lib/Medicos  # Directorio que contiene el Dockerfile
      dockerfile: Dockerfile  # Nombre del archivo Dockerfile
    ports:
      - "3700:3700"  # Puerto del host mapeado al contenedor
    container_name: medicos_service

  pacientes:
    build:
      context: ./lib/Pacientes  # Directorio que contiene el Dockerfile
      dockerfile: Dockerfile  # Nombre del archivo Dockerfile
    ports:
      - "3701:3701"  # Puerto del host mapeado al contenedor
    container_name: pacientes_service
